config/routes.rb
Rails.application.routes.draw do
  resources :customers do
    resources :orders, only: [:index]
    member do
      post :block
    end
  end

end

app/models/customer.rb
# app/models/customer.rb

class Customer < ApplicationModel
  belongs_to :operator
  has_many :locations
  has_many :orders
end

app/models/order.rb
# app/models/order.rb

class order < ApplicationModel
  belongs_to :customer
  enum status: { pending: 0, success: 1, failed: 2, rolled_back: 3 }
end

app/controllers/customer_controller.rb
class CustomersController < ApplicationController
  def index
    # @customers = Customer.order(:name)
    @customers = Customer.includes(:operator, :locations).order(:name)
  end

  def block
    @customer = Customer.find(params[:id])
    @customer.update(blocked: true)
    redirect_to @customer, notice: 'Cliente bloqueado com sucesso.'
  end
end

app/controllers/orders_controller.rb
# app/controllers/orders_controller.rb

class OrdersController < ApplicationController
  def index
    @customer = Customer.find(params[:customer_id])
    @orders = @customer.orders
  end
end

app/views/customer/index.html.erb
<!-- app/views/customer/index.html.erb -->
<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Operador</th>
      <th>Locais</th>
      <th>Pedidos</th> <!-- Nova coluna para o link de pedidos -->
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.operator.name %></td>
        <td><%= customer.locations.map(&:name).join(', ') %></td>
        <td><%= link_to 'Ver Pedidos', customer_orders_path(customer) %></td> <!-- Link para a página de pedidos -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/index.html.erb
<!-- app/views/orders/index.html.erb -->

<h1>Lista de Pedidos do Cliente: <%= @customer.name %></h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Valor</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= number_to_currency(order.value) %></td>
        <td><%= order.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>